server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ch11_liveclassapiproject
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      '[hibernate.format_sql]': true
logging:
  config:
    classpath: logback-spring.xml